create table if not exists user_profile
(
    id            integer generated by default as identity
        primary key,
    username      varchar(100) not null,
    password      varchar      not null,
    name          varchar      not null,
    year_of_birth integer      not null,
    email         varchar,
    role          varchar      not null
);