create table if not exists movie_actor
(
    id integer generated by default as identity primary key,
    movie_id integer not null
        references movie,
    actor_id integer not null
        references actor,
    constraint unique_actors unique (movie_id, actor_id)
);