create table movie
(
    id                 integer generated by default as identity
        primary key,
    name               varchar(100) not null,
    director_id        integer
                                    references director
                                        on delete set null,
    movie_genre        varchar(100) not null,
    rate               real
        constraint movie_rate_check
            check (rate > (0)::double precision)
    constraint movie_rate_check1
        check (rate <= (10)::double precision),
info               varchar,
poster             varchar      not null,
like_count         integer,
year_of_production integer      not null
);